package org.codehaus.plexus.ldapserver.ldapv3;

//-----------------------------------------------------------------------------
//   NOTE: this is a machine generated file - editing not recommended
//
//   File: ./src/org/codehaus/ldapv3/AttributeValueAssertion.java
//
//   Java class for ASN.1 definition AttributeValueAssertion as defined in
//   module LDAPv3.
//   This file was generated by Snacc for Java at Fri Jul  2 18:01:43 1999
//   Snacc for Java - Andreas Schade (SAN/ZRL)
//-----------------------------------------------------------------------------

// Import PrintStream class for print methods

import com.ibm.asn1.*;
import com.ibm.util.*;

import java.io.PrintStream;

/** This class represents the ASN.1 SEQUENCE type <tt>AttributeValueAssertion</tt>.
 * For each sequence member, sequence classes contain a
 * public member variable of the corresponding Java type.
 * @author Snacc for Java
 * @version Fri Jul  2 18:01:43 1999

 */

public class AttributeValueAssertion implements LDAPv3
{

    /** member variable representing the sequence member attributeDesc of type byte[] */
    public byte[] attributeDesc;
    /** member variable representing the sequence member assertionValue of type byte[] */
    public byte[] assertionValue;

    /** default constructor */
    public AttributeValueAssertion()
    {
    }

    /** copy constructor */
    public AttributeValueAssertion( AttributeValueAssertion arg )
    {
        attributeDesc = new byte[arg.attributeDesc.length];
        System.arraycopy( arg.attributeDesc, 0, attributeDesc, 0, arg.attributeDesc.length );
        assertionValue = new byte[arg.assertionValue.length];
        System.arraycopy( arg.assertionValue, 0, assertionValue, 0, arg.assertionValue.length );
    }

    /** decoding method.
     * @param dec
     *        decoder object derived from com.ibm.asn1.ASN1Decoder
     * @exception com.ibm.asn1.ASN1Exception
     *            decoding error
     */
    public void decode( ASN1Decoder dec ) throws ASN1Exception
    {
        int seq_nr = dec.decodeSequence();
        attributeDesc = dec.decodeOctetString();
        assertionValue = dec.decodeOctetString();
        dec.endOf( seq_nr );
    }

    /** encoding method.
     * @param enc
     *        encoder object derived from com.ibm.asn1.ASN1Encoder
     * @exception com.ibm.asn1.ASN1Exception
     *            encoding error
     */
    public void encode( ASN1Encoder enc ) throws ASN1Exception
    {
        int seq_nr = enc.encodeSequence();
        enc.encodeOctetString( attributeDesc );
        enc.encodeOctetString( assertionValue );
        enc.endOf( seq_nr );
    }

    /** default print method (variable indentation)
     * @param os
     *        PrintStream representing the print destination (file, etc)
     */
    public void print( PrintStream os )
    {
        print( os, 0 );
    }

    /** print method (variable indentation)
     * @param os
     *        PrintStream representing the print destination (file, etc)
     * @param indent
     *        number of blanks that preceed each output line.
     */
    public void print( PrintStream os, int indent )
    {
        os.println( "{ -- SEQUENCE --" );
        for ( int ii = 0; ii < indent + 2; ii++ ) os.print( ' ' );
        os.print( "attributeDesc = " );
        try
        {
            ( new HexOutputStream( os ) ).write( attributeDesc );
        }
        catch ( java.io.IOException ex )
        {
            os.print( "( unprintable OCTET STRING value )" );
        }
        os.println( ',' );

        for ( int ii = 0; ii < indent + 2; ii++ ) os.print( ' ' );
        os.print( "assertionValue = " );
        try
        {
            ( new HexOutputStream( os ) ).write( assertionValue );
        }
        catch ( java.io.IOException ex )
        {
            os.print( "( unprintable OCTET STRING value )" );
        }

        os.println();
        for ( int ii = 0; ii < indent; ii++ ) os.print( ' ' );
        os.print( '}' );
    }
}
