package org.codehaus.plexus.ldapserver.ldapv3;

//-----------------------------------------------------------------------------
//   NOTE: this is a machine generated file - editing not recommended
//
//   File: LDAPv3
//
//   Java base interface for ASN.1 constants as defined in
//   module LDAPv3.
//   This file was generated by Snacc for Java at Fri Jul  2 18:01:43 1999
//   Snacc for Java - Andreas Schade (SAN/ZRL)
//-----------------------------------------------------------------------------

import com.ibm.asn1.*;
import com.ibm.util.*;

/** The package <tt>org.codehaus.ldapv3</tt> contains constant value definitions which
 * are defined in this Java class. Therefore, all other classes in this
 * package inherit from this class rather than directly from
 * <tt>ANS1Type</tt>.
 */

public interface LDAPv3 extends ASN1Type
{

    // value defs

    /** constant definition for <tt>MAXINT</tt>. */
    static public final java.math.BigInteger MAXINT = java.math.BigInteger.valueOf( (long) 2147483647 );

}
