package org.codehaus.plexus.ldapserver.ldapv3;

//-----------------------------------------------------------------------------
//   NOTE: this is a machine generated file - editing not recommended
//
//   File: ./src/org/codehaus/ldapv3/ModifyRequestSeqOfSeq.java
//
//   Java class for ASN.1 definition ModifyRequestSeqOfSeq as defined in
//   module LDAPv3.
//   This file was generated by Snacc for Java at Fri Jul  2 18:01:43 1999
//   Snacc for Java - Andreas Schade (SAN/ZRL)
//-----------------------------------------------------------------------------

// Import PrintStream class for print methods

import com.ibm.asn1.*;
import com.ibm.util.*;

import java.io.PrintStream;

/** This class represents the ASN.1 SEQUENCE type <tt>ModifyRequestSeqOfSeq</tt>.
 * For each sequence member, sequence classes contain a
 * public member variable of the corresponding Java type.
 * @author Snacc for Java
 * @version Fri Jul  2 18:01:43 1999

 */

public class ModifyRequestSeqOfSeq implements LDAPv3
{

    /** member variable representing the sequence member operation of type ModifyRequestSeqOfSeqEnum */
    public ModifyRequestSeqOfSeqEnum operation = new ModifyRequestSeqOfSeqEnum();
    /** member variable representing the sequence member modification of type AttributeTypeAndValues */
    public AttributeTypeAndValues modification = new AttributeTypeAndValues();

    /** default constructor */
    public ModifyRequestSeqOfSeq()
    {
    }

    /** copy constructor */
    public ModifyRequestSeqOfSeq( ModifyRequestSeqOfSeq arg )
    {
        operation = new ModifyRequestSeqOfSeqEnum( arg.operation );
        modification = new AttributeTypeAndValues( arg.modification );
    }

    /** decoding method.
     * @param dec
     *        decoder object derived from com.ibm.asn1.ASN1Decoder
     * @exception com.ibm.asn1.ASN1Exception
     *            decoding error
     */
    public void decode( ASN1Decoder dec ) throws ASN1Exception
    {
        int seq_nr = dec.decodeSequence();
        operation.decode( dec );
        modification.decode( dec );
        dec.endOf( seq_nr );
    }

    /** encoding method.
     * @param enc
     *        encoder object derived from com.ibm.asn1.ASN1Encoder
     * @exception com.ibm.asn1.ASN1Exception
     *            encoding error
     */
    public void encode( ASN1Encoder enc ) throws ASN1Exception
    {
        int seq_nr = enc.encodeSequence();
        operation.encode( enc );
        modification.encode( enc );
        enc.endOf( seq_nr );
    }

    /** default print method (variable indentation)
     * @param os
     *        PrintStream representing the print destination (file, etc)
     */
    public void print( PrintStream os )
    {
        print( os, 0 );
    }

    /** print method (variable indentation)
     * @param os
     *        PrintStream representing the print destination (file, etc)
     * @param indent
     *        number of blanks that preceed each output line.
     */
    public void print( PrintStream os, int indent )
    {
        os.println( "{ -- SEQUENCE --" );
        for ( int ii = 0; ii < indent + 2; ii++ ) os.print( ' ' );
        os.print( "operation = " );
        operation.print( os, indent + 2 );
        os.println( ',' );

        for ( int ii = 0; ii < indent + 2; ii++ ) os.print( ' ' );
        os.print( "modification = " );
        modification.print( os, indent + 2 );

        os.println();
        for ( int ii = 0; ii < indent; ii++ ) os.print( ' ' );
        os.print( '}' );
    }
}
