package org.codehaus.plexus.ldapserver.ldapv3;

//-----------------------------------------------------------------------------
//   NOTE: this is a machine generated file - editing not recommended
//
//   File: ./src/org/codehaus/ldapv3/DelRequest.java
//
//   Java class for ASN.1 definition DelRequest as defined in
//   module LDAPv3.
//   This file was generated by Snacc for Java at Fri Jul  2 18:01:43 1999
//   Snacc for Java - Andreas Schade (SAN/ZRL)
//-----------------------------------------------------------------------------

// Import PrintStream class for print methods

import com.ibm.asn1.*;
import com.ibm.util.*;

import java.io.PrintStream;

/** This class represents the ASN.1 simple definition <tt>DelRequest</tt>.
 * Simple classes contain a member variable <tt>value</tt> of the
 * type that is FINALLY referred to.
 * @author Snacc for Java
 * @version Fri Jul  2 18:01:43 1999

 */

public class DelRequest implements LDAPv3
{

    public byte[] value;

    /** default constructor */
    public DelRequest()
    {
    }

    public DelRequest( byte[] arg )
    {
        value = arg;
    }

    /** copy constructor */
    public DelRequest( DelRequest arg )
    {
        value = new byte[arg.value.length];
        System.arraycopy( arg.value, 0, value, 0, arg.value.length );
    }

    /** decoding method.
     * @param dec
     *        decoder object derived from com.ibm.asn1.ASN1Decoder
     * @exception com.ibm.asn1.ASN1Exception
     *            decoding error
     */
    public void decode( ASN1Decoder dec ) throws ASN1Exception
    {
        dec.nextIsImplicit( dec.makeTag( dec.APPLICATION_TAG_CLASS, 10 ) );
        value = dec.decodeOctetString();
    }

    /** encoding method.
     * @param enc
     *        encoder object derived from com.ibm.asn1.ASN1Encoder
     * @exception com.ibm.asn1.ASN1Exception
     *            encoding error
     */
    public void encode( ASN1Encoder enc ) throws ASN1Exception
    {
        enc.nextIsImplicit( enc.makeTag( enc.APPLICATION_TAG_CLASS, 10 ) );
        enc.encodeOctetString( value );
    }

    /** default print method (variable indentation)
     * @param os
     *        PrintStream representing the print destination (file, etc)
     */
    public void print( PrintStream os )
    {
        print( os, 0 );
    }

    /** print method (variable indentation)
     * @param os
     *        PrintStream representing the print destination (file, etc)
     * @param indent
     *        number of blanks that preceed each output line.
     */
    public void print( PrintStream os, int indent )
    {
        try
        {
            ( new HexOutputStream( os ) ).write( value );
        }
        catch ( java.io.IOException ex )
        {
            os.print( "( unprintable OCTET STRING value )" );
        }
    }
}
